name: Timesheet Check
on:
  schedule:
    # Run every Monday at 9 AM (adjust to your timezone)
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  check-timesheets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd scripts
          npm install
      
      - name: Run timesheet check
        env:
          MESSAGING_PLATFORM: ${{ secrets.MESSAGING_PLATFORM }}
          KIMAI_URL: ${{ secrets.KIMAI_URL }}
          KIMAI_API_KEY: ${{ secrets.KIMAI_API_KEY }}
          KIMAI_USERNAME: ${{ secrets.KIMAI_USERNAME }}
          KIMAI_PASSWORD: ${{ secrets.KIMAI_PASSWORD }}
          PUMBLE_API_KEY: ${{ secrets.PUMBLE_API_KEY }}
          BOT_IDENTITY: ${{ secrets.BOT_IDENTITY }}
          BLOODHUNTER_EMAIL: ${{ secrets.BLOODHUNTER_EMAIL }}
          BLOODHUNTER_ID: ${{ secrets.BLOODHUNTER_ID }}
          BLOODHUNTER_API_KEY: ${{ secrets.BLOODHUNTER_API_KEY }}
          AGENTSMITH_EMAIL: ${{ secrets.AGENTSMITH_EMAIL }}
          AGENTSMITH_ID: ${{ secrets.AGENTSMITH_ID }}
          AGENTSMITH_API_KEY: ${{ secrets.AGENTSMITH_API_KEY }}
          DEV_CHANNEL_ID: ${{ secrets.DEV_CHANNEL_ID }}
          DESIGN_CHANNEL_ID: ${{ secrets.DESIGN_CHANNEL_ID }}
          ADMIN_CHANNEL_ID: ${{ secrets.ADMIN_CHANNEL_ID }}
          MANAGER_EMAIL: ${{ secrets.MANAGER_EMAIL }}
          EMPLOYEE_MAPPING: ${{ secrets.EMPLOYEE_MAPPING }}
        run: |
          cd scripts
          node kimai-timesheet-bot.js check