name: Monday Pay Period Reminder

on:
  schedule:
    # Run every Monday at 6 AM CST (11 AM UTC during DST, 12 PM UTC during standard time)
    # This sends the 1-hour advance notice to Mikhail
    - cron: '0 11 * * 1'
    
    # Run every Monday at 7 AM CST (12 PM UTC during DST, 1 PM UTC during standard time)  
    # This sends the main reminders to channels
    - cron: '0 12 * * 1'
    
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode (bypasses date check)'
        required: false
        default: 'false'
        type: boolean
      action:
        description: 'Which action to run'
        required: false
        default: 'both'
        type: choice
        options:
          - 'both'          # Send advance notice + main reminders
          - 'advance-only'  # Only send advance notice to Mikhail
          - 'main-only'     # Only send main reminders to channels

jobs:
  send-advance-notice:
    # Run at 6 AM or when manually triggered
    if: |
      (github.event_name == 'schedule' && contains(github.event.schedule, '0 11')) ||
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.action == 'both' || github.event.inputs.action == 'advance-only'))
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd bots
        npm install
    
    - name: Send 1-Hour Advance Notice to Mikhail
      env:
        # Bot configuration
        BOT_IDENTITY: ${{ secrets.BOT_IDENTITY || 'agentsmith' }}
        BOT_NAME: ${{ secrets.BOT_NAME || 'Agent Smith' }}
        BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
        BOT_ID: ${{ secrets.BOT_ID }}
        
        # Messaging platform
        MESSAGING_PLATFORM: ${{ secrets.MESSAGING_PLATFORM || 'pumble' }}
        
        # Pumble credentials
        PUMBLE_API_KEY: ${{ secrets.PUMBLE_API_KEY }}
        PUMBLE_BASE_URL: ${{ secrets.PUMBLE_BASE_URL || 'https://pumble.com/api/v1' }}
        
        # Mikhail's info
        MIKHAIL_PUMBLE_ID: ${{ secrets.MIKHAIL_PUMBLE_ID || '66908542f1798a06218c1fc5' }}
        MIKHAIL_EMAIL: ${{ secrets.MIKHAIL_EMAIL }}
        
      run: |
        cd bots/monday-reminder
        echo "📨 Sending 1-hour advance notice to Mikhail..."
        node monday-reminder.js advance

  send-main-reminders:
    # Run at 7 AM or when manually triggered
    if: |
      (github.event_name == 'schedule' && contains(github.event.schedule, '0 12')) ||
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.action == 'both' || github.event.inputs.action == 'main-only'))
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd bots
        npm install
    
    - name: Send Monday Reminders to Channels
      env:
        # Bot configuration
        BOT_IDENTITY: ${{ secrets.BOT_IDENTITY || 'agentsmith' }}
        BOT_NAME: ${{ secrets.BOT_NAME || 'Agent Smith' }}
        BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
        BOT_ID: ${{ secrets.BOT_ID }}
        
        # Messaging platform
        MESSAGING_PLATFORM: ${{ secrets.MESSAGING_PLATFORM || 'pumble' }}
        
        # Pumble credentials
        PUMBLE_API_KEY: ${{ secrets.PUMBLE_API_KEY }}
        PUMBLE_BASE_URL: ${{ secrets.PUMBLE_BASE_URL || 'https://pumble.com/api/v1' }}
        
        # Channel IDs (hardcoded since they don't change)
        DEV_CHANNEL_ID: ${{ secrets.DEV_CHANNEL_ID || '66934de10aeebd36fe26f468' }}
        DESIGN_CHANNEL_ID: ${{ secrets.DESIGN_CHANNEL_ID || '66b6450b791a8769092d6f89' }}
        
        # Mikhail's info
        MIKHAIL_PUMBLE_ID: ${{ secrets.MIKHAIL_PUMBLE_ID || '66908542f1798a06218c1fc5' }}
        MIKHAIL_EMAIL: ${{ secrets.MIKHAIL_EMAIL }}
        
        # Kimai configuration (required by config but not used for reminders)
        KIMAI_URL: ${{ secrets.KIMAI_URL || 'https://kimai.starthub.academy' }}
        KIMAI_API_KEY: ${{ secrets.KIMAI_API_KEY || 'dummy-key-for-reminder' }}
        
      run: |
        cd bots/monday-reminder
        if [ "${{ github.event.inputs.test_mode }}" == "true" ]; then
          echo "📤 Running in test mode..."
          node monday-reminder.js test
        else
          echo "📤 Sending reminders to #dev and #design channels..."
          node monday-reminder.js send
        fi