name: Checks

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION || '22' }}

      - name: Install dependencies
        working-directory: ./bots
        run: npm install

      - name: Run Jest tests
        working-directory: ./bots
        run: |
          npm test -- --ci --passWithNoTests
        env:
          NODE_ENV: test
          CI: true

      - name: Test Summary
        if: always()
        run: |
          echo "✅ Tests completed" >> $GITHUB_STEP_SUMMARY

  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION || '22' }}

      - name: Install dependencies
        working-directory: ./bots
        run: npm install

      - name: Run linter
        working-directory: ./bots
        run: npm run lint --if-present || echo "No lint script"

  security:
    name: Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for secrets
        run: |
          echo "🔍 Checking for exposed secrets..."
          if grep -r "AGENTSMITH_API_KEY=" bots/ --include="*.js" --exclude-dir=node_modules | grep -v "process.env"; then
            echo "❌ Found exposed API keys!"
            exit 1
          fi
          echo "✅ No exposed secrets found"